apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 18.1.9
    helm:
      valuesFiles:
        - kubernetes/infra/operators/postgres/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres
    createNamespace: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
