apiVersion: v1
kind: Secret
metadata:
  name: cuecards-secrets
  namespace: cuecards
type: Opaque
stringData:
  # Postgres
  POSTGRES_PASSWORD: "<your-postgres-password>"
  POSTGRES_USER: "cuecards"
  POSTGRES_DB: "cuecards_db"

  # Redis
  REDIS_PASSWORD: "<your-redis-password>"

  # Email
  EMAIL_USER: "cuecards2000@gmail.com"
  EMAIL_PASSWORD: "6Oslikov"

  # AWS SES
  AWS_ACCESS_KEY_ID: "<your-aws-access-key-id>"
  AWS_SECRET_ACCESS_KEY: "<your-aws-secret-access-key>"

  # Default user
  DEFAULT_USER_PASSWORD: "<your-default-user-password>"
