apiVersion: v1
kind: Secret
metadata:
  name: cuecards-secrets
  namespace: cuecards
type: Opaque
stringData:
  POSTGRES_DB: "cuecards_db"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "999"

  # Redis
  REDIS_PASSWORD: "123456"

  # Email
  EMAIL_USER: "cuecards2000@gmail.com"
  EMAIL_PASSWORD: "123456"

  # AWS SES
  AWS_ACCESS_KEY_ID: "<your-aws-access-key-id>"
  AWS_SECRET_ACCESS_KEY: "<your-aws-secret-access-key>"

  # Default user
  DEFAULT_USER_PASSWORD: "123456"
