apiVersion: v1
kind: Secret
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiR1JELTEiLCJwYXNzd29yZCI6ImdocF9RTkFwOWlNOVVETHhuZWlzeDlYa2xvZzZ3ZU80MjkwcmVFMGciLCJhdXRoIjoiUjFKRUxURTZaMmh3WDFGT1FYQTVhVTA1VlVSTWVHNWxhWE40T1ZocmJHOW5ObmRsVHpReU9UQnlaVVV3Wnc9PSJ9fX0=
metadata:
  name: ghcr-secrets
  namespace: cuecards
type: kubernetes.io/dockerconfigjson
