apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: postgres
type: Opaque
stringData:
  postgresql-username: "cuecards"
  postgresql-database: "cuecards_db"
  postgresql-password: "123456"
