apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: postgres
type: Opaque
stringData:
  # Postgres superuser password (used for all database operations)
  postgres-password: "password" # Password for 'postgres' superuser (default PostgreSQL superuser)
