apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: postgres
type: Opaque
stringData:
  postgresql-password: "<your-postgres-password>"
  postgresql-username: "cuecards"
  postgresql-database: "cuecards_db"
