apiVersion: apps/v1
kind: Deployment
metadata:
  name: cuecards-web
  namespace: cuecards
  labels:
    app: cuecards-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cuecards-web
  template:
    metadata:
      labels:
        app: cuecards-web
    spec:
      imagePullSecrets:
        - name: ghcr-secrets
      containers:
        - name: cuecards-web
          image: ghcr.io/grd-1/cuecards-web:b5fd73162b69e45a955a4076441ea5f9ae1f5a0e
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          env:
            - name: APP_WEB_ID
              value: "a7ef69ad-708d-4f8e-b20c-98b99e36ffdc"
            - name: APP_WEB_NAME
              value: "cuecards-web"
            - name: APP_WEB_NAME_UI
              value: "CUE CARDS"
