apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cuecards-web-ingress
  namespace: cuecards
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - cuecards.online
    secretName: web-tls
  rules:
    - host: cuecards.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cuecards-web
                port:
                  number: 80
